// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUcLXJsUoPqruoMFAgjNODm6NJTSB73z4',
    appId: '1:1058300006721:web:885df655773e11e65811c0',
    messagingSenderId: '1058300006721',
    projectId: 'targetly-2ff93',
    authDomain: 'targetly-2ff93.firebaseapp.com',
    storageBucket: 'targetly-2ff93.firebasestorage.app',
    measurementId: 'G-RF358VRC6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKHmzrYrVpAYjtUwi5blBIn9b7MOPefJ0',
    appId: '1:1058300006721:android:e4af6af36e497fd55811c0',
    messagingSenderId: '1058300006721',
    projectId: 'targetly-2ff93',
    storageBucket: 'targetly-2ff93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8wbpDdrKUQWZvQRvhIo0Zkq-ejRD2OCs',
    appId: '1:1058300006721:ios:571bd16e2aa371c75811c0',
    messagingSenderId: '1058300006721',
    projectId: 'targetly-2ff93',
    storageBucket: 'targetly-2ff93.firebasestorage.app',
    iosBundleId: 'com.example.targetly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8wbpDdrKUQWZvQRvhIo0Zkq-ejRD2OCs',
    appId: '1:1058300006721:ios:571bd16e2aa371c75811c0',
    messagingSenderId: '1058300006721',
    projectId: 'targetly-2ff93',
    storageBucket: 'targetly-2ff93.firebasestorage.app',
    iosBundleId: 'com.example.targetly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUcLXJsUoPqruoMFAgjNODm6NJTSB73z4',
    appId: '1:1058300006721:web:2b345b636f997ede5811c0',
    messagingSenderId: '1058300006721',
    projectId: 'targetly-2ff93',
    authDomain: 'targetly-2ff93.firebaseapp.com',
    storageBucket: 'targetly-2ff93.firebasestorage.app',
    measurementId: 'G-0N786TFND3',
  );
}
